### ISSUE TITLE
Feature request: pass initial evaluation points as argument

### ISSUE THREAD

**Issue by fredcallaway** [jbrea/BayesianOptimization.jl#12]
Sometimes one already has the function precomputed at some set of points. It would be nice to be able to pass these to the optimizer somehow. I thought I could just do...

```
o = BOpt(...)
xs = [rand(dim) for i in 1:500];
ys = Int(opt.sense) .* f.(xs);
BayesianOptimization.update!(o.model, hcat(xs...), ys)
boptimize!(opt)
```

but I realize that this make boptimize skip `initialise_function!` (and hence, `nlopt_setup`). I'm actually not sure how the code above runs without error... In any case, maybe it makes sense to include this as part of the standard interface?

**Comment by jbrea** [comment]
Did you actually run this example? I think it should run just fine, since `update` does not increment the iterations counter and therefore `initialise_function!` should still be called. See also #10.

I guess we need better documentation of this situation.

**Comment by jbrea** [comment]
Ps. I just saw that there is nevertheless and issue with ElasticGPEs. This should be fixed and better documented now.

**Comment by fredcallaway** [comment]
Ah, my mistake. I saw that the logs started at iteration `max_iterations`, making me think it skipped the initialization. But now I see the logs begin at that point even without the warm-start. Thanks!
