### ISSUE TITLE
Absolute value in expression

### ISSUE THREAD

**Issue by ngiann** [jbrea/BayesianOptimization.jl#21]
I noticed that at line
https://github.com/jbrea/BayesianOptimization.jl/blob/5ce078b50c1447860e5465eae0fe0be0600b671a/src/acquisitionfunctions.jl#L49

one takes the absolute value ``abs(μ - a.τ)`` as opposed to perhaps ``μ - a.τ`` which is what equation (4) in "A Tutorial on Bayesian Optimization of..." suggests. 

I am looking at the code to see whether the repository could help with using BO on my problem. 
Thanks for your time.

**Comment by jbrea** [comment]
Sorry for the delay. This seems to be wrong. I don't know what this `abs` is searching there :) In practice it doesn't make a big difference though. Thanks for reporting!
